name: Lint
on:
  push:
  pull_request:
jobs:
  job:
    runs-on: ubuntu-latest
    timeout-minutes: 3
    steps:
      - uses: actions/checkout@v1
      - name: Prepare
        run: npm i
      - name: Lint
        run: npm run lint